### ISSUE TITLE
week03

### ISSUE THREAD

**Issue by panicfrog** [algorithm015/-algorithm015#30]
#学号: G20200343130013
#姓名: D8Ge
#班级: 15期-1班
#语言: cpp
#作业链接: https://github.com/panicfrog/-algorithm015/tree/master/Week_03
#总结链接: https://github.com/panicfrog/-algorithm015/tree/master/Week_03

**Comment by bugxch** [comment]
#学号: G20200343120122
#姓名: 宇宙无敌大魔王
#班级: 15期-2班
#语言: cpp
#作业链接: https://github.com/bugxch/-algorithm015/tree/master/Week_03/code
#总结链接: https://github.com/bugxch/-algorithm015/blob/master/Week_03/README.md
